// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKd6xpNahBxUNzLZUScX0ZpgHNADQt25k',
    appId: '1:61882917594:web:d738930a8376231bb7fbe3',
    messagingSenderId: '61882917594',
    projectId: 'store-816fb',
    authDomain: 'store-816fb.firebaseapp.com',
    storageBucket: 'store-816fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhaigGqkIB6tDYfkJpMckuneImC4Dz_Y',
    appId: '1:61882917594:android:ff01ae7f23bd6cb2b7fbe3',
    messagingSenderId: '61882917594',
    projectId: 'store-816fb',
    storageBucket: 'store-816fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXm0JSKiL2UXKfrZOqQSfJrB7Q8tNp9I',
    appId: '1:61882917594:ios:67e4eef7550fe9afb7fbe3',
    messagingSenderId: '61882917594',
    projectId: 'store-816fb',
    storageBucket: 'store-816fb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
